version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  express:
    container_name: express
    depends_on:
      - db
    image: 'node:20'
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/db
      - JWT_SECRET=secret
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npx prisma generate
        npx prisma migrate deploy
        npm run dev

  react:
    container_name: react
    image: 'node:20'
    ports:
      - "80:3000"
    volumes:
      - ./front:/app
    depends_on:
      - express
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev